<html>

  <head>

    <title>bcmp</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>

    <link rel="stylesheet" type="text/css" href="include/css/00_reset.css">
    <link rel="stylesheet" type="text/css" href="include/css/10_home-default.css">
    <link rel="stylesheet" type="text/css" href="include/css/20_fluff.css">
    
    <link rel="apple-touch-icon" sizes="180x180" href="include/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="include/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="include/icons/favicon-16x16.png">
    <link rel="manifest" href="include/icons/site.webmanifest">
    <link rel="mask-icon" href="include/icons/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

  </head>


  <body>

    <div id="div-body-wrapper" style="width: 100%;"> <!-- Div Header -->

      <div id="div-header-logo"><span id="span-header-logo">$ ./bcmp</span></div>

      <div id="div-col-01">
        <div> 
          <h3>Benchmark Compare Tool</h3>
          <b>bcmp</b> is a tool to extract program features generated by LLVM -stats and compare them. The project is currently under development — once finished this page will be updated to contain the tool, along with an interface that will take user input, extract the same features and show a detailed comparison with the existing benchmarks. There's a
          <a href="http://cuda.dcc.ufmg.br/angha/gallery.html" target=_blank>gallery</a>
          with some images of an alpha version.
        </div>
      </div> <!-- div-col-01 -->

      <div id="div-col-02">

        <div id="div-tab-control" class="TabControl">

          <div id="header">
            <h3>Available Benchmarks</h3>
            The highlighted benchmarks are available for download.
            Others will be uploaded in a near future.
          </div>
          <br>

          <ul>

            <li>
              <label for="checkbox-angha-1-2" class="label-expand">
                <img src="include/icons/expand.svg" height="15" class="icon-expand"></img>
                <!--<input type="checkbox" id="checkbox-angha-1-1" style="display:none;">-->
                <span>Single Function Angha Benchmark</span>
              </label>
              <input type="checkbox" id="checkbox-angha-1-2" style="display:none;">
              <div class="div-bdescription">
                The 10.000 largest compilable C functions extracted from
                programs, mined from popular github repositories.
                <br><a href="http://cuda.dcc.ufmg.br/angha/src/largest10k.tar.gz">download</a>
              </div>
            </li>
            
            <li>
              <label for="checkbox-angha2" class="label-expand">
                <img src="include/icons/expand.svg" height="15" class="icon-expand"></img>
                Single Function Angha Benchmark (Large)
              </label>
              <input type="checkbox" id="checkbox-angha2" style="display:none;">
              <div class="div-bdescription">
                Several (aprox. 530.000) single function C files extracted from
                programs, mined from popular github repositories.
                <br><a href="http://cuda.dcc.ufmg.br/angha/src/all_angha_kernels.tar.gz">download</a>
              </div>
            </li>
            
            <li>
              <label for="checkbox-angha3" class="label-expand">
                <img src="include/icons/expand.svg" height="15" class="icon-expand"></img>
                LLVM Test-Suite and more
              </label>
              <input type="checkbox" id="checkbox-angha3" style="display:none;">
              <div class="div-bdescription">
                Collection of programs that come with the LLVM Test-Suit with some additions.
                More details can be found 
                <a href="https://github.com/lac-dcc/Benchmarks">here</a>.
                <br><a href="http://cuda.dcc.ufmg.br/angha/src/tfbenchs.tar.gz">download</a>
              </div>
            </li>

          </ul>

        </div> <!-- div-tab-control -->

      </div> <!-- div-col-02 -->

      <div id="div-footer">
        <hr>
        <a href="http://lac.dcc.ufmg.br/index.html">Other projects from our lab</a>
      </div>

    </div> <!-- div-body-wrapper -->

  </body>

</html>


<!-- Global site tag (gtag.js) - Google Analytics
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-8958830-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-8958830-2');
</script>-->

<!--
  <div class="help-tip">
    <p>Tips!</p>
  </div>
-->